### PR TITLE
add aws iam instance profile outputs

### PR DESCRIPTION
**Pull request by nicgrayson**

### CODE REVIEW

**Comment by brikis98** [comment]
Tests failed due to the AWS Provider 3.x release. Fixes in https://github.com/hashicorp/terraform-aws-nomad/pull/73. We'll need to get that merged first.

**Comment by brikis98** [comment]
https://github.com/hashicorp/terraform-aws-nomad/pull/73 is now merged. Could you rebase and I can kick off tests again?

**Comment by nicgrayson** [comment]
@brikis98 rebased

**Comment by brikis98** [comment]
Great, thanks. Kicking off tests now.

**Comment by brikis98** [comment]
Tests passed. Merging now.

**Pull request merged**
