### PR TITLE
Bump tf to version 1.0

### PR DESCRIPTION
**Pull request by bwhaley**
Updates tests to use Terraform 1.0.

### CODE REVIEW

**Review by zackproser — APPROVED** [review]
LGTM

**Review by brikis98 — APPROVED** [review]
Changes LGTM! I'll kick off tests.

**Comment by brikis98** [comment]
@bwhaley Looks like there were some test failures

**Comment by bwhaley** [comment]
Mind kicking off the tests again?

**Comment by brikis98** [comment]
Tests are running again!

**Comment by bwhaley** [comment]
Looks like the test failed again, but it seems unrelated to this change. I see that the same test fails on the master branch quite often.

**Comment by brikis98** [comment]
Re-running to see if it was a transient issue.

**Comment by brikis98** [comment]
Tests failed again:

```
│ Error: Your query returned no results. Please change your search criteria and try again.
│ 
│   with data.aws_ami.nomad_consul,
│   on main.tf line 35, in data "aws_ami" "nomad_consul":
│   35: data "aws_ami" "nomad_consul" {
│ 
╵}
    destroy.go:11: 
        	Error Trace:	destroy.go:11
        	            				nomad_helpers.go:63
        	            				test_structure.go:27
        	            				panic.go:613
        	            				testing.go:741
        	            				apply.go:15
        	            				nomad_helpers.go:101
        	            				test_structure.go:27
        	            				nomad_helpers.go:81
        	            				nomad_consul_cluster_colocated_test.go:19
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; ╷
        	            	│ Error: Your query returned no results. Please change your search criteria and try again.
        	            	│ 
        	            	│   with data.aws_ami.nomad_consul,
        	            	│   on main.tf line 35, in data "aws_ami" "nomad_consul":
        	            	│   35: data "aws_ami" "nomad_consul" {
        	            	│ 
        	            	╵}
        	Test:       	TestNomadConsulClusterColocatedAmazonLinux2Amd64Ami
--- FAIL: TestNomadConsulClusterColocatedAmazonLinux2Amd64Ami (387.16s)
```

I think the issue may be that we don't have an AMI published for `ap-northeast-3`. Perhaps exclude that region from the tests?

**Comment by bwhaley** [comment]
Added `ap-northeast-3` to the forbidden regions.

**Comment by brikis98** [comment]
Thanks. Running tests once more.

**Comment by brikis98** [comment]
OK, tests passed! Merging now.

**Comment by brikis98** [comment]
https://github.com/hashicorp/terraform-aws-nomad/releases/tag/v0.10.0

**Pull request merged**
