### PR TITLE
Update nomad CLI usage in nomad-examples-helper.sh

### PR DESCRIPTION
**Pull request by mattreduce**
Replaces some deprecated CLI commands with current usage

### CODE REVIEW

**Review by brikis98 — COMMENTED** [review]
Thanks for the PR!

Could you update the READMEs too? I think we have a mention of `server-members` and other older commands in one or two places.

**Comment by mattreduce** [comment]
@brikis98 sure thing! I'll update any other mentions I can find. Thanks for the review. 😄

**Comment by mattreduce** [comment]
@brikis98 I looked аround for other deprecated dasherized `nomad` CLI commands and updated them in https://github.com/hashicorp/terraform-aws-nomad/pull/82/commits/e50504b608fc3ffb83492f1d72f8101865d83902 😄👍

**Review by brikis98 — APPROVED** [review]
Perfect, thank you! I'll kick off tests now.

**Comment by brikis98** [comment]
Tests passed! Merging now.

**Comment by mattreduce** [comment]
Thanks for the review @brikis98 😄

**Pull request merged**
